export const cards = [
    { rank: '2', suit: 'Hearts', value: 2, color:'text-red-600' },
    { rank: '3', suit: 'Hearts', value: 3, color:'text-red-600'  },
    { rank: '4', suit: 'Hearts', value: 4, color:'text-red-600'  },
    { rank: '5', suit: 'Hearts', value: 5, color:'text-red-600'  },
    { rank: '6', suit: 'Hearts', value: 6, color:'text-red-600'  },
    { rank: '7', suit: 'Hearts', value: 7, color:'text-red-600'  },
    { rank: '8', suit: 'Hearts', value: 8, color:'text-red-600'  },
    { rank: '9', suit: 'Hearts', value: 9, color:'text-red-600'  },
    { rank: '10', suit: 'Hearts', value: 10, color:'text-red-600'  },
    { rank: 'J', suit: 'Hearts', value: 10, color:'text-red-600'  },
    { rank: 'Q', suit: 'Hearts', value: 10, color:'text-red-600'  },
    { rank: 'K', suit: 'Hearts', value: 10, color:'text-red-600'  },
    { rank: 'A', suit: 'Hearts', value: 11, secondValue: 1, color:'text-red-600'  },
    { rank: '2', suit: 'Diamonds', value: 2, color:'text-red-600'  },
    { rank: '3', suit: 'Diamonds', value: 3, color:'text-red-600'  },
    { rank: '4', suit: 'Diamonds', value: 4, color:'text-red-600'  },
    { rank: '5', suit: 'Diamonds', value: 5, color:'text-red-600'  },
    { rank: '6', suit: 'Diamonds', value: 6, color:'text-red-600'  },
    { rank: '7', suit: 'Diamonds', value: 7, color:'text-red-600'  },
    { rank: '8', suit: 'Diamonds', value: 8, color:'text-red-600'  },
    { rank: '9', suit: 'Diamonds', value: 9, color:'text-red-600'  },
    { rank: '10', suit: 'Diamonds', value: 10, color:'text-red-600'  },
    { rank: 'J', suit: 'Diamonds', value: 10, color:'text-red-600'  },
    { rank: 'Q', suit: 'Diamonds', value: 10, color:'text-red-600'  },
    { rank: 'K', suit: 'Diamonds', value: 10, color:'text-red-600'  },
    { rank: 'A', suit: 'Diamonds', value: 11, secondValue: 1, color:'text-red-600'  },
    { rank: '2', suit: 'Clubs', value: 2, color:'text-black'  },
    { rank: '3', suit: 'Clubs', value: 3, color:'text-black' },
    { rank: '4', suit: 'Clubs', value: 4, color:'text-black' },
    { rank: '5', suit: 'Clubs', value: 5, color:'text-black' },
    { rank: '6', suit: 'Clubs', value: 6, color:'text-black' },
    { rank: '7', suit: 'Clubs', value: 7, color:'text-black' },
    { rank: '8', suit: 'Clubs', value: 8, color:'text-black' },
    { rank: '9', suit: 'Clubs', value: 9, color:'text-black' },
    { rank: '10', suit: 'Clubs', value: 10, color:'text-black' },
    { rank: 'J', suit: 'Clubs', value: 10, color:'text-black' },
    { rank: 'Q', suit: 'Clubs', value: 10, color:'text-black' },
    { rank: 'K', suit: 'Clubs', value: 10, color:'text-black' },
    { rank: 'A', suit: 'Clubs', value: 11, secondValue: 1, color:'text-black' },
    { rank: '2', suit: 'Spades', value: 2, color:'text-black' },
    { rank: '3', suit: 'Spades', value: 3, color:'text-black' },
    { rank: '4', suit: 'Spades', value: 4, color:'text-black' },
    { rank: '5', suit: 'Spades', value: 5, color:'text-black' },
    { rank: '6', suit: 'Spades', value: 6, color:'text-black' },
    { rank: '7', suit: 'Spades', value: 7, color:'text-black' },
    { rank: '8', suit: 'Spades', value: 8, color:'text-black' },
    { rank: '9', suit: 'Spades', value: 9, color:'text-black' },
    { rank: '10', suit: 'Spades', value: 10, color:'text-black' },
    { rank: 'J', suit: 'Spades', value: 10, color:'text-black' },
    { rank: 'Q', suit: 'Spades', value: 10, color:'text-black' },
    { rank: 'K', suit: 'Spades', value: 10, color:'text-black' },
    { rank: 'A', suit: 'Spades', value: 11, secondValue:1, color:'text-black'},
    { rank: 'A', suit: 'Spades', value: 11, secondValue:1, color:'text-black'},

  ];
  